baseURL = "https://radiorab.github.io/"
languageCode = "en-us"
title = "radioRAB"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

[params]
    author = "radioRAB"
    description = "La radio que t'écoutes quand tu n'as rien à boire!"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    css = ["css/extra.css"]
    copyright = "Ce site a été généré avec [Hugo](https://gohugo.io) et le thème [Minimal](https://github.com/calintat/minimal). Par défaut, les contenus présentés sur ce site sont licensiés sous [CC-BY](https://creativecommons.org/licenses/by/4.0/)."
    profilePic = "img/logo_rab_r.png"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "À propos"
    weight = 2

[[menu.main]]
    url = "/radio/"
    name = "Radio"
    weight = 2

[[menu.main]]
    url = "/podcasts/"
    name = "Podcasts"
    weight = 3

[[menu.main]]
    url = "/opinions/"
    name = "Opinions"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:rab.radiofficiel@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/radioRAB/"
    name = "github"
    weight = 2

# [[menu.icon]]
#     url = "https://twitter.com/username/"
#     name = "twitter"
#     weight = 3
